CREATE TABLE MP_BOARD(                          -- 게시글 작성
    BNO NUMBER              NOT NULL,           -- 게시판 번호
    TITLE VARCHAR2(100)     NOT NULL,           -- 게시판 제목
    CONTENT VARCHAR2(2000)  NOT NULL,           -- 게시판 내용
    WRITER VARCHAR2(100)    NOT NULL,           -- 작성자
    REGDATE DATE            DEFAULT SYSDATE,    -- 등록일
    PRIMARY KEY (BNO)                           -- 기본키
);

CREATE SEQUENCE MP_BOARD_SEQ -- 게시판 번호를 1부터 자동으로 증가
START WITH 1
INCREMENT BY 1;

INSERT INTO MP_BOARD(BNO, TITLE, CONTENT, WRITER)
    VALUES (MP_BOARD_SEQ.NEXTVAL, '제목', '내용', '임동우');

SELECT * FROM MP_BOARD;


CREATE TABLE MP_REPLY(                          -- 게시글 댓글
    BNO NUMBER              NOT NULL,
    RNO NUMBER              NOT NULL,
    CONTENT VARCHAR2(1000)  NOT NULL,
    WRITER VARCHAR2(50)     NOT NULL,
    REGDATE DATE            DEFAULT SYSDATE,
    PRIMARY KEY(BNO, RNO)
);

ALTER TABLE MP_REPLY ADD CONSTRAINT MP_REPLY_BNO FOREIGN KEY(BNO)
REFERENCES MP_BOARD(BNO);

CREATE SEQUENCE MP_REPLY_SEQ
START WITH 1
MINVALUE 0;

INSERT INTO MP_REPLY(BNO, RNO, CONTENT, WRITER)
    VALUES(31, MP_REPLY_SEQ.NEXTVAL, 'test', 'writer');
    
SELECT RNO, CONTENT, WRITER, REGDATE
  FROM MP_REPLY
 WHERE BNO = 31;


CREATE TABLE MP_MEMBER (                        -- 회원(로그인, 회원가입)
    USERID      VARCHAR2(40)  NOT NULL,
    USERPASS    VARCHAR2(100) NOT NULL,
    USERNAME    VARCHAR2(40)  NOT NULL,
    REGDATEE    DATE          DEFAULT SYSDATE,
    PRIMARY KEY(USERID)
);

INSERT INTO MP_MEMBER(USERID, USERPASS, USERNAME)
    VALUES('asd', '123', '임동우');
    
SELECT * FROM MP_MEMBER;


UPDATE MP_BOARD SET TITLE = '번호 1번' WHERE BNO = 1;

DELETE FROM MP_BOARD WHERE BNO = 4;

COMMIT;